name: Windows_Build

on:
  workflow_dispatch:
    inputs:
      configuration:
        description: 'Configuration'
        required: true
        default: 'Release'
        type: choice
        options:
        - Release
        - Debug
      platform:
        description: 'Platform'
        required: true
        default: 'Win32'
        type: choice
        options:
        - Win32
      architecture:
        description: 'Architecture'
        required: true
        default: x64
        type: choice
        options:
        - x64
        - x86
        - arm64
      keep:
        description: 'Disposition Keep: "artifact" | Publish: BIN\NT'
        required: true
        default: 'Keep'
        type: choice
        options:
        - 'Discard'
        - 'Keep'
        - 'Publish'
      inspect:
        description: 'Build directory contents listing'
        required: true
        default: 'exclude'
        type: choice
        options:
        - Exclude
        - Include

  pull_request:
    types: closed
    branches: [ 'master' ]

#  [push,pull_request]:
#    branches: [ 'master' ]

env:
  SOLUTION_FILE:       'Visual Studio Projects\Simh.ci.sln'
  BUILD_CONFIGURATION: ${{ inputs.configuration      || 'Release' }}
  BUILD_PLATFORM:      ${{ inputs.platform           || 'Win32' }}
  BUILD_ARCH:          ${{ inputs.architecture       || 'x64' }}
  INSPECT:             ${{ inputs.inspect            || 'Exclude' }}
  KEEP:                ${{ inputs.keep               || 'onMerge' }}

permissions:
  contents: write

jobs:
  build-on-windows:
    environment: open-simh-ci
    runs-on: windows-latest

    steps:
    - name: 'Checkout branch'
      uses: actions/checkout@v3
    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.1
      with:
        msbuild-architecture: ${{ env.BUILD_ARCH }}
    - name: Build Simulators
      shell: cmd
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: |
        msbuild "${{env.SOLUTION_FILE}}" -property:Configuration=${{env.BUILD_CONFIGURATION}} -property:Platform=${{env.BUILD_PLATFORM}}
    - name: Inspect result tree
      if: ${{ env.INSPECT == 'Include' }}
      shell: cmd
      run: dir /S BIN\NT
    - name: Upload Results as ZIP artifact
      if: ${{ env.KEEP != 'Discard'  && ( env.KEEP == 'Keep' || ( github.event_name == 'pull_request' && github.event.pull_request.merged == true ) ) }}
      uses: actions/upload-artifact@v3.1.2
      with:
        name: ${{env.BUILD_PLATFORM}}-${{env.BUILD_ARCH}}-${{env.BUILD_CONFIGURATION}}
        path: BIN\NT\${{env.BUILD_PLATFORM}}-${{env.BUILD_CONFIGURATION}}\*.exe
        if-no-files-found: error
        retention-days: 90
    - name: Commit new executables to BIN
      if: ${{ env.KEEP == 'Publish' }}
      shell: cmd
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: |
        mkdir BIN\NT\${{env.BUILD_PLATFORM}}-${{env.BUILD_ARCH}}-${{env.BUILD_CONFIGURATION}}
        move  BIN\NT\${{env.BUILD_PLATFORM}}-${{env.BUILD_CONFIGURATION}}\*.exe BIN\NT\${{env.BUILD_PLATFORM}}-${{env.BUILD_ARCH}}-${{env.BUILD_CONFIGURATION}}
        git config user.name "${{ github.actor }}.${{ github.job }}"
        git config user.email "admin@opensimh.org"
        git add -f BIN\NT\${{env.BUILD_PLATFORM}}-${{env.BUILD_ARCH}}-${{env.BUILD_CONFIGURATION}}\*.exe
        git commit -m "Update windows binaries for ${{env.BUILD_PLATFORM}}-${{env.BUILD_ARCH}}-${{env.BUILD_CONFIGURATION}}"
        git push
